### ISSUE TITLE
Still confused on the Durafet calibration..

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-geoduck-oa#1]
When I thought I knew what the plan was - make buffer - look up what pH is for given temperature, calibrate probes to this one point...

Rhonda's protocol states the following

> Wait until the pH stabilizes before pressing enter to change the pH. Use the “pH Calculator (TRIS/AMP)” worksheet to determine what your pH should be at the temperature your TRIS buffer is at. Press enter and follow the prompts until you see CALIBRATION COMPLETE, then exit. **For example, if the Durafet reads 8.40 in your TRIS buffer and your TRIS pH should be 8.27 according to your calibration curve, that is a SUCCESS, calibrate down to 8.27**! You are now in TOTAL scale. Hooray!

@hputnam any insight ....

**Comment by hputnam** [comment]
RE the calibration. This is what I was thinking...

Make the Tris buffer with the recipe to match the salinity of the seawater (I believe 27.5). 
Use the pH_Calc_Tris_Buffer.xlsx (in protocol folder) to calculate the pH on the total scale for the salinity (27.5) and temperature (measured room temperature).
Calibrate the Durafet Honeywell with a single point calibration using the Tris buffer with calculated pH.

There is a 2 point calibration that is possible with Tris and AMP, but I don’t think we need this based on the discussions for Durafet calibration.

Best Wishes,

Hollie 

---

Hollie Putnam
University of Hawaii
Hawaii Institute of Marine Biology
46-007 Lilipuna Rd. 
Kaneohe, HI 96744
Phone: 808-554-1462
Fax: 808-236-7443

http://www.hollieputnam.com

https://www.google.com/calendar/embed?src=hollieputnam%40gmail.com&ctz=Pacific/Honolulu 

---

**Comment by sr320** [comment]
We did the single point calibration with the Tris buffer as above. Rhonda has questioned if we did NBS too? 
https://plus.google.com/u/0/106492099842577316500/posts/Avwk8TQ2bTi

**Comment by hputnam** [comment]
I am not sure what the point of the NBS calibration would be… If you do another calibration you are erasing the prior one.  Also the ionic strength of the NBS buffer is different than that of the tris so it seems you would be creating problems for the electrode. I have never done a NBS before a tris calibration, it has been one or the other. I would love to hear the rationale for it.

Yui (from the Martz lab) explicitly said "I would strongly recommend not using NBS buffers, once durafets are making measurements in SW. The two solutions have very different ionic strengths, so it could take hours to restabilize in the new solution."
